spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobs_app
    username: postgres
    password: "*Mareen7#"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true